version: 2

# CircleCI doesn't handle large file sets properly for local builds
# https://github.com/CircleCI-Public/circleci-cli/issues/281#issuecomment-472808051
localCheckout: &localCheckout
  run: |-
    PROJECT_PATH=$(cd ${CIRCLE_WORKING_DIRECTORY}; pwd)
    mkdir -p ${PROJECT_PATH}
    cd /tmp/_circleci_local_build_repo
    git ls-files -z | xargs -0 -s 2090860 tar -c | tar -x -C ${PROJECT_PATH}
    cp -a /tmp/_circleci_local_build_repo/.git ${PROJECT_PATH}

.openssl_job: &openssljob
  docker:
    - image: ${IMAGE}
  steps:
    - checkout # change this from "checkout" to "*localCheckout" when running CircleCI locally
    - run:
        name: Clone liboqs
        command: ./oqs-test/clone_liboqs.sh # unconditional checkout to test for changes there
    - run:
        name: Build liboqs
        command: .circleci/git_no_checkin_in_last_day.sh || (./oqs-test/build_liboqs.sh)
    - run:
        name: Configure and build OpenSSL
        command: .circleci/git_no_checkin_in_last_day.sh || (./config ${OPENSSL_CONFIGURE_ARGS} && make -j2)
    - run:
        name: Check that OpenSSL speed works for all KEMS
        command: .circleci/git_no_checkin_in_last_day.sh || (env LD_LIBRARY_PATH=".:./oqs/lib" apps/openssl speed -seconds 1 oqskem)
    - run:
        name: Check that OpenSSL speed works for all signatures
        # Disabling cleanup on Linux because of picnic-induced memory glitch:
        command: .circleci/git_no_checkin_in_last_day.sh || (env LD_LIBRARY_PATH=".:./oqs/lib" OPENSSL_NO_CLEANUP=1 apps/openssl speed -seconds 1 oqssig)
    - run:
        name: Run connection and CMS tests
        command: .circleci/git_no_checkin_in_last_day.sh && mkdir -p oqs-test/test-results || (make run-${CONN_TEST_TYPE}-conn-tests && make run-cms-tests)
    - store_test_results: # Note that this command will fail when running CircleCI locally, that is expected behaviour
        path: oqs-test/tmp/test-results

.macopenssl_job: &macopenssljob
    macos:
       xcode: "11.3.0"
    steps:
        - checkout # change this from "checkout" to "*localCheckout" when running CircleCI locally
        - run:
            name: Install dependencies
            command: |
              .circleci/git_no_checkin_in_last_day.sh || (
              brew update &&
              brew unlink python@2 &&
              brew install cmake ninja &&
              pip3 install --user pytest pytest-xdist
              )
        - run:
            name: Clone liboqs
            command: ./oqs-test/clone_liboqs.sh # unconditional checkout to test for changes there
        - run:
            name: Build liboqs
            command: .circleci/git_no_checkin_in_last_day.sh || (./oqs-test/build_liboqs.sh)
        - run:
            name: Configure and build OpenSSL
            command: .circleci/git_no_checkin_in_last_day.sh || (./config ${OPENSSL_CONFIGURE_ARGS} && make -j2)
        - run:
            name: Check that OpenSSL speed works for all KEMS
            command: .circleci/git_no_checkin_in_last_day.sh || (env DYLD_LIBRARY_PATH=".:./oqs/lib" apps/openssl speed -seconds 1 oqskem)
        - run:
            name: Check that OpenSSL speed works for all signatures
            # Test only the sig that doesn't cause memory problems on macOS:
            command: .circleci/git_no_checkin_in_last_day.sh || (env DYLD_LIBRARY_PATH=".:./oqs/lib" apps/openssl speed -seconds 1 dilithium2)
        - run:
            name: Run connection and CMS tests
            command: .circleci/git_no_checkin_in_last_day.sh && mkdir -p oqs-test/test-results || (make run-${CONN_TEST_TYPE}-conn-tests && make run-cms-tests)
        - store_test_results: # Note that this command will fail when running CircleCI locally, that is expected behaviour
            path: oqs-test/tmp/test-results

jobs:
  debian_buster-shared_oqs-static_ossl-full:
    <<: *openssljob
    environment:
      IMAGE: openquantumsafe/ci-debian-buster-amd64:latest
      LIBOQS_LIBTYPE: shared
      CONN_TEST_TYPE: full
      OPENSSL_CONFIGURE_ARGS: no-shared
  ubuntu_bionic-shared_oqs-shared_ossl-full:
    <<: *openssljob
    environment:
      IMAGE: openquantumsafe/ci-ubuntu-bionic-x86_64:latest
      LIBOQS_LIBTYPE: shared
      CONN_TEST_TYPE: full
  ubuntu_bionic-static_oqs-static_ossl-basic:
    <<: *openssljob
    environment:
      IMAGE: openquantumsafe/ci-ubuntu-bionic-x86_64:latest
      OPENSSL_CONFIGURE_ARGS: no-shared
      CONN_TEST_TYPE: basic
  macOS-shared_oqs-shared_ossl-basic:
    <<: *macopenssljob
    environment:
      LIBOQS_LIBTYPE: shared
      CONN_TEST_TYPE: basic
  macOS-static_oqs-static_ossl-full:
    <<: *macopenssljob
    environment:
      CONN_TEST_TYPE: full
      OPENSSL_CONFIGURE_ARGS: no-shared

workflows:
  version: 2
  build:
    jobs:
      - macOS-shared_oqs-shared_ossl-basic
      - ubuntu_bionic-shared_oqs-shared_ossl-full
      - ubuntu_bionic-static_oqs-static_ossl-basic
  nightly:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only:
                - OQS-OpenSSL_1_1_1-stable
    jobs:
      - macOS-shared_oqs-shared_ossl-basic
      - macOS-static_oqs-static_ossl-full
      - debian_buster-shared_oqs-static_ossl-full
      - ubuntu_bionic-shared_oqs-shared_ossl-full
      - ubuntu_bionic-static_oqs-static_ossl-basic

